### PR TITLE
0.19.11

### PR DESCRIPTION
**Pull request by ghost**
Hi. This is username9999. This is my first ever Github pull request. What am I supposed to do now?
I could push my changes, but you also made some. Conflicts could happen

I can't upload the files I want to have for review. Do I just list my changes?

Mod compatibility:
done Krastorio 2:
--sand, glass, and silicon
		change internal names to distinguish from K2 versions
--(not done)disable other recipes and items where applicable
--ensure vehicles can use quantum fuel (like aircrafts)
--add support for Krastorio2 equipment into darkstar vehicle grid

done Rampant:
--(New Enemies) biters and spitters and worms and associated spawners
		only recipes for spawners and worms
		(might not work)tint blue for distinguishing from enemies
--add alien-weapons techs
--(done)need to add vanilla units to make this support work
(note: blue tinting doesn't seem to work for me. Maybe it's tinted differently
	since Veden updated Rampant)

done RSO:
--lead, lithium, and gold don't spawn. Add extraction recipes for extraction machine
	and adjust extraction machine recipe

(done)bio as science requirement:
--all bio weapons (alien-weapons 1-4)
--neuro-perceptual resource gathering 2-4 (neural-miners)
--neuro-perceptual item teleportation

(done)add space science ingredient
--Linari Space station (space-station1)
.

### CODE REVIEW

**Comment by H4ckerxx44** [comment]
I suggest you reading [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by ghost** [comment]
I guess I just create a fork and do my changes there.

**Comment by ghost** [comment]
I made my changes in the fork. Unfortunately I did in the wrong branch. 0.19.10. I think we should have branches "Test" and "Release" instead of having a branch for every version.

**Comment by ghost** [comment]
I think it would be better if I didn't work with you on this. The mod is being "fixed", not added to or changed, which is an additional goal I have. I think the thing I did, adding mod compatibility, is not fixing but adding,

**Comment by ghost** [comment]
Also, I keep making mistakes like committing to the wrong branch and having to redo code over and over and the fact changes are being made to 0.19.11 is making me think there'll be conflicts in changes and blah blah blah. It's irritating me.

**Comment by ghost** [comment]
OK. I've had some time to calm down. Let me try this again... I'll do a "git checkout 0.19.11" and make my changes in the fork. Then I'll commit, then you can review said changes and merge if it's ok.

**Comment by ghost** [comment]
Closing request as I made a correct one. I made sure the 0.19.11 code was modified, not the 0.19.10 branch.

**Pull request closed without merging**
