### PR TITLE
0.19.11 Request

### PR DESCRIPTION
**Pull request by ghost**
Added vanilla enemy units for spawning. Some krastorio 2 support. Added Rampant New Enemies units. Neural science pack added as ingredient to some neural-related techs. Added space science pack to Linari Space station tech as ingredient.

Notes:
Vanilla biters and spitters can be placed, but Rampant New Enemies do not have recipes and thus cannot be placed. They use the corresponding spawners. Worms are turrets so they can all be placed and picked up (so goes for spawners). Biters and spitters cannot be picked up.
Units should have blue tinting for recognition.

Oh. Resource Spawner Overhaul support was added. Lead, gold, and lithium can be extracted from ore extractor. Ore extractor recipe changed to not use one of these ores.

Another compatibility addition: Krastorio 2 equipment categories added to Darkstar vehice equipment grid.

### CODE REVIEW

**Comment by H4ckerxx44** [comment]
Is it possible for you to break this down into seperate pull requests and commits?

A pull request should have one topic and one topic only, same for commits. 

For example, make `Krastorio Support` would be an own pull request, `Added Rampant New Enemies units` too.

**Comment by ghost** [comment]
I guess it's possible. I did it all in go because a lot of the stuff happens in data-final-fixes and it was a goal to get at least these changes through.

**Comment by ghost** [comment]
Man. I really don't want to go through this again just to comment stuff out temporarily.

**Comment by ghost** [comment]
Ok. So I made the changes. I guess we can add in RSO and Rampant in the next 2 commits. They'll be rapid-fire commits since I literally just commented out stuff.

**Comment by H4ckerxx44** [comment]
I'd suggest you deleting your fork and start again, this is just kinda too messy to really see whats going on, especially when others look at the code changes.

Create a fork, do one thing and do a PR, like one feature at a time.

**Comment by ghost** [comment]
*sigh* ok.

**Pull request closed without merging**
